services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: sonarsoftware/customerportal:next
    container_name: sonar-customerportal
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/caddy/data:/data
      - ./public/assets/img/logo.png:/var/www/html/public/assets/img/logo.png
      - ./public/assets/img/cover.png:/var/www/html/public/assets/img/cover.png
      - ./public/assets/fcclabels:/var/www/html/public/assets/fcclabels
      - storage:/var/www/html/storage
    env_file:
      - .env
    environment:
      ENABLE_SSL: "${ENABLE_SSL}"
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7.0.11-alpine
    restart: always

volumes:
  storage:
    driver: local
